### PR TITLE
Cache improvements on CI

### LINKED ISSUE #90: [CI] Share build artifacts
Currently `test_zemu` and `build_ledger` both build the app binaries, but don't share it in any way...
This means we are duplicating the CI work needed to build these binaries, but it would be nice to have these binaries shared somehow so that they are only built once

### LINKED ISSUE #91: Cache rust dependencies
Currently when building the app Cargo will try to update it's index and fetch all dependencies, which can take some time (10 minutes) as the index is really big.

We could make use of a cache to reduce this step to a few seconds when `rust/Cargo.lock`'s hash hasn't changed (no dependency change). It's not common to change our dependencies so we would hit the cache fairly often.

### PR DESCRIPTION
**Pull request by emmanuelm41**
Closes #90 
Closes #91

### CODE REVIEW

**Comment by jleni** [comment]
it seems that elf binaries are missing so test are not running?

**Comment by emmanuelm41** [comment]
@jleni, if you check closely, you will see the elf files are being cached. However, the zemu_test doesn't find it. The builder_ledger job is actually using cached files from previous jobs. The only difference I see between them is the running environment. The only job which is not using a container is test_zemu

**Comment by jleni** [comment]
The missing files seem to come from `path: '/home/runner/work/ledger-tezos/ledger-tezos/legacy/output/app.elf'` 
That path is not cached only the standard apps but not legacy apps

**Comment by emmanuelm41** [comment]
> The missing files seem to come from `path: '/home/runner/work/ledger-tezos/ledger-tezos/legacy/output/app.elf'`
> That path is not cached only the standard apps but not legacy apps

Check these images...

image

image

**Comment by emmanuelm41** [comment]
I ran the zemu_test inside a container, and the cache was found... I cannot understand why, because nobody says nothing about being cache related to the environment where it was generated...

**Comment by emmanuelm41** [comment]
It may be related to https://github.com/actions/cache/issues/591#issuecomment-845121153

**Comment by emmanuelm41** [comment]
It was related to those issues indeed. Now the cache was found and used... This is another issue related to it: https://github.com/actions/cache/issues/580

**Review by becominginsane — COMMENTED** [review]
Looks super nice! 
I'm trying to understand a few things: are the legacy app binaries cached now ? In the "cache multiple paths" step I only see our app's binaries...

**Comment by emmanuelm41** [comment]
> Looks super nice!
> I'm trying to understand a few things: are the legacy app binaries cached now ? In the "cache multiple paths" step I only see our app's binaries...

You are right, I forgot that path. Is it correct this one **legacy/output**?

**Comment by becominginsane** [comment]
Yes that's right, the files are `legacy/output/app.elf` and `legacy/output/app_baking.elf`

**Comment by emmanuelm41** [comment]
@becominginsane something happens with legacy app building process. I moved it from zemu_test to build_lerger job. 

image

image

**Comment by becominginsane** [comment]
That doesn't look right, it should do the build. I'll check it later and get back to you.

**Comment by emmanuelm41** [comment]
> That doesn't look right, it should do the build. I'll check it later and get back to you.

The only difference I see is one is running inside ubuntu-latest (zemu_test) and the other inside zemu/rust-ci (a container)

**Comment by jleni** [comment]
image

This seems the same issue as before

**Comment by jleni** [comment]
it looks like your are trying to recover the cache in a directory that does not exist?
maybe creating the dir before restoring works?

**Comment by emmanuelm41** [comment]
> it looks like your are trying to recover the cache in a directory that does not exist?
> maybe creating the dir before restoring works?

Did you check this? https://github.com/Zondax/ledger-tezos/pull/93#issuecomment-890082374. The legacy build process says "up to date" and it seems not to be builded.

**Comment by emmanuelm41** [comment]
@becominginsane Is there something I can do here?

**Comment by becominginsane** [comment]
No, not really.
We have to determine why the X app is failing to build before we can proceed

**Pull request merged**
